package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_ANQI.
 */
public class Da_anqi {

    private Long id;
    private String hkaqsx;
    private String hkaq;
    private String hksj;
    private String hkazwz;

    public Da_anqi() {
    }

    public Da_anqi(Long id) {
        this.id = id;
    }

    public Da_anqi(Long id, String hkaqsx, String hkaq, String hksj, String hkazwz) {
        this.id = id;
        this.hkaqsx = hkaqsx;
        this.hkaq = hkaq;
        this.hksj = hksj;
        this.hkazwz = hkazwz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHkaqsx() {
        return hkaqsx;
    }

    public void setHkaqsx(String hkaqsx) {
        this.hkaqsx = hkaqsx;
    }

    public String getHkaq() {
        return hkaq;
    }

    public void setHkaq(String hkaq) {
        this.hkaq = hkaq;
    }

    public String getHksj() {
        return hksj;
    }

    public void setHksj(String hksj) {
        this.hksj = hksj;
    }

    public String getHkazwz() {
        return hkazwz;
    }

    public void setHkazwz(String hkazwz) {
        this.hkazwz = hkazwz;
    }

}
