package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_BT.
 */
public class Da_bt {

    private Long id;
    private String jqid;
    private String lcid;
    private String sblx;
    private String lydz;
    private String lybm;
    private String sjbz;

    public Da_bt() {
    }

    public Da_bt(Long id) {
        this.id = id;
    }

    public Da_bt(Long id, String jqid, String lcid, String sblx, String lydz, String lybm, String sjbz) {
        this.id = id;
        this.jqid = jqid;
        this.lcid = lcid;
        this.sblx = sblx;
        this.lydz = lydz;
        this.lybm = lybm;
        this.sjbz = sjbz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJqid() {
        return jqid;
    }

    public void setJqid(String jqid) {
        this.jqid = jqid;
    }

    public String getLcid() {
        return lcid;
    }

    public void setLcid(String lcid) {
        this.lcid = lcid;
    }

    public String getSblx() {
        return sblx;
    }

    public void setSblx(String sblx) {
        this.sblx = sblx;
    }

    public String getLydz() {
        return lydz;
    }

    public void setLydz(String lydz) {
        this.lydz = lydz;
    }

    public String getLybm() {
        return lybm;
    }

    public void setLybm(String lybm) {
        this.lybm = lybm;
    }

    public String getSjbz() {
        return sjbz;
    }

    public void setSjbz(String sjbz) {
        this.sjbz = sjbz;
    }

}
