package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_HKSJ.
 */
public class Da_hksj {

    private Long id;
    private String value;
    private String sj;
    private String cgqsx;
    private String sjlx;

    public Da_hksj() {
    }

    public Da_hksj(Long id) {
        this.id = id;
    }

    public Da_hksj(Long id, String value, String sj, String cgqsx, String sjlx) {
        this.id = id;
        this.value = value;
        this.sj = sj;
        this.cgqsx = cgqsx;
        this.sjlx = sjlx;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getSj() {
        return sj;
    }

    public void setSj(String sj) {
        this.sj = sj;
    }

    public String getCgqsx() {
        return cgqsx;
    }

    public void setCgqsx(String cgqsx) {
        this.cgqsx = cgqsx;
    }

    public String getSjlx() {
        return sjlx;
    }

    public void setSjlx(String sjlx) {
        this.sjlx = sjlx;
    }

}
