package com.huimv.yzzs.db.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huimv.yzzs.db.entity.Da_hksj;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DA_HKSJ.
*/
public class Da_hksjDao extends AbstractDao<Da_hksj, Long> {

    public static final String TABLENAME = "DA_HKSJ";

    /**
     * Properties of entity Da_hksj.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
        public final static Property Sj = new Property(2, String.class, "sj", false, "SJ");
        public final static Property Cgqsx = new Property(3, String.class, "cgqsx", false, "CGQSX");
        public final static Property Sjlx = new Property(4, String.class, "sjlx", false, "SJLX");
    }


    public Da_hksjDao(DaoConfig config) {
        super(config);
    }
    
    public Da_hksjDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DA_HKSJ' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'VALUE' TEXT," + // 1: value
                "'SJ' TEXT," + // 2: sj
                "'CGQSX' TEXT," + // 3: cgqsx
                "'SJLX' TEXT);"); // 4: sjlx
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DA_HKSJ'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Da_hksj entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
 
        String sj = entity.getSj();
        if (sj != null) {
            stmt.bindString(3, sj);
        }
 
        String cgqsx = entity.getCgqsx();
        if (cgqsx != null) {
            stmt.bindString(4, cgqsx);
        }
 
        String sjlx = entity.getSjlx();
        if (sjlx != null) {
            stmt.bindString(5, sjlx);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Da_hksj readEntity(Cursor cursor, int offset) {
        Da_hksj entity = new Da_hksj( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // value
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sj
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cgqsx
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // sjlx
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Da_hksj entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSj(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCgqsx(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSjlx(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Da_hksj entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Da_hksj entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
