package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_PH.
 */
public class Da_ph {

    private Long id;
    private String hkphsx;
    private String hkph;
    private String hksj;
    private String hkazwz;

    public Da_ph() {
    }

    public Da_ph(Long id) {
        this.id = id;
    }

    public Da_ph(Long id, String hkphsx, String hkph, String hksj, String hkazwz) {
        this.id = id;
        this.hkphsx = hkphsx;
        this.hkph = hkph;
        this.hksj = hksj;
        this.hkazwz = hkazwz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHkphsx() {
        return hkphsx;
    }

    public void setHkphsx(String hkphsx) {
        this.hkphsx = hkphsx;
    }

    public String getHkph() {
        return hkph;
    }

    public void setHkph(String hkph) {
        this.hkph = hkph;
    }

    public String getHksj() {
        return hksj;
    }

    public void setHksj(String hksj) {
        this.hksj = hksj;
    }

    public String getHkazwz() {
        return hkazwz;
    }

    public void setHkazwz(String hkazwz) {
        this.hkazwz = hkazwz;
    }

}
