package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_QK_SHUIYA.
 */
public class Da_qk_shuiya {

    private Long id;
    private String qksysx;
    private String qksy;
    private String qksj;
    private String qkazwz;

    public Da_qk_shuiya() {
    }

    public Da_qk_shuiya(Long id) {
        this.id = id;
    }

    public Da_qk_shuiya(Long id, String qksysx, String qksy, String qksj, String qkazwz) {
        this.id = id;
        this.qksysx = qksysx;
        this.qksy = qksy;
        this.qksj = qksj;
        this.qkazwz = qkazwz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQksysx() {
        return qksysx;
    }

    public void setQksysx(String qksysx) {
        this.qksysx = qksysx;
    }

    public String getQksy() {
        return qksy;
    }

    public void setQksy(String qksy) {
        this.qksy = qksy;
    }

    public String getQksj() {
        return qksj;
    }

    public void setQksj(String qksj) {
        this.qksj = qksj;
    }

    public String getQkazwz() {
        return qkazwz;
    }

    public void setQkazwz(String qkazwz) {
        this.qkazwz = qkazwz;
    }

}
