package com.huimv.yzzs.db.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huimv.yzzs.db.entity.Da_qk_shuiliu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DA_QK_SHUILIU.
*/
public class Da_qk_shuiliuDao extends AbstractDao<Da_qk_shuiliu, Long> {

    public static final String TABLENAME = "DA_QK_SHUILIU";

    /**
     * Properties of entity Da_qk_shuiliu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Qkslsx = new Property(1, String.class, "qkslsx", false, "QKSLSX");
        public final static Property Qksl = new Property(2, String.class, "qksl", false, "QKSL");
        public final static Property Qksj = new Property(3, String.class, "qksj", false, "QKSJ");
        public final static Property Qkazwz = new Property(4, String.class, "qkazwz", false, "QKAZWZ");
    }


    public Da_qk_shuiliuDao(DaoConfig config) {
        super(config);
    }
    
    public Da_qk_shuiliuDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DA_QK_SHUILIU' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'QKSLSX' TEXT," + // 1: qkslsx
                "'QKSL' TEXT," + // 2: qksl
                "'QKSJ' TEXT," + // 3: qksj
                "'QKAZWZ' TEXT);"); // 4: qkazwz
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DA_QK_SHUILIU'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Da_qk_shuiliu entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String qkslsx = entity.getQkslsx();
        if (qkslsx != null) {
            stmt.bindString(2, qkslsx);
        }
 
        String qksl = entity.getQksl();
        if (qksl != null) {
            stmt.bindString(3, qksl);
        }
 
        String qksj = entity.getQksj();
        if (qksj != null) {
            stmt.bindString(4, qksj);
        }
 
        String qkazwz = entity.getQkazwz();
        if (qkazwz != null) {
            stmt.bindString(5, qkazwz);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Da_qk_shuiliu readEntity(Cursor cursor, int offset) {
        Da_qk_shuiliu entity = new Da_qk_shuiliu( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // qkslsx
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // qksl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // qksj
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // qkazwz
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Da_qk_shuiliu entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQkslsx(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setQksl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQksj(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQkazwz(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Da_qk_shuiliu entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Da_qk_shuiliu entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
