package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_QK_SHUILIU.
 */
public class Da_qk_shuiliu {

    private Long id;
    private String qkslsx;
    private String qksl;
    private String qksj;
    private String qkazwz;

    public Da_qk_shuiliu() {
    }

    public Da_qk_shuiliu(Long id) {
        this.id = id;
    }

    public Da_qk_shuiliu(Long id, String qkslsx, String qksl, String qksj, String qkazwz) {
        this.id = id;
        this.qkslsx = qkslsx;
        this.qksl = qksl;
        this.qksj = qksj;
        this.qkazwz = qkazwz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQkslsx() {
        return qkslsx;
    }

    public void setQkslsx(String qkslsx) {
        this.qkslsx = qkslsx;
    }

    public String getQksl() {
        return qksl;
    }

    public void setQksl(String qksl) {
        this.qksl = qksl;
    }

    public String getQksj() {
        return qksj;
    }

    public void setQksj(String qksj) {
        this.qksj = qksj;
    }

    public String getQkazwz() {
        return qkazwz;
    }

    public void setQkazwz(String qkazwz) {
        this.qkazwz = qkazwz;
    }

}
