package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_SHIDU.
 */
public class Da_shidu {

    private Long id;
    private String hksdsx;
    private String hksd;
    private String hksj;
    private String hkazwz;

    public Da_shidu() {
    }

    public Da_shidu(Long id) {
        this.id = id;
    }

    public Da_shidu(Long id, String hksdsx, String hksd, String hksj, String hkazwz) {
        this.id = id;
        this.hksdsx = hksdsx;
        this.hksd = hksd;
        this.hksj = hksj;
        this.hkazwz = hkazwz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHksdsx() {
        return hksdsx;
    }

    public void setHksdsx(String hksdsx) {
        this.hksdsx = hksdsx;
    }

    public String getHksd() {
        return hksd;
    }

    public void setHksd(String hksd) {
        this.hksd = hksd;
    }

    public String getHksj() {
        return hksj;
    }

    public void setHksj(String hksj) {
        this.hksj = hksj;
    }

    public String getHkazwz() {
        return hkazwz;
    }

    public void setHkazwz(String hkazwz) {
        this.hkazwz = hkazwz;
    }

}
