package com.huimv.yzzs.db.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huimv.yzzs.db.entity.Da_shidu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DA_SHIDU.
*/
public class Da_shiduDao extends AbstractDao<Da_shidu, Long> {

    public static final String TABLENAME = "DA_SHIDU";

    /**
     * Properties of entity Da_shidu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Hksdsx = new Property(1, String.class, "hksdsx", false, "HKSDSX");
        public final static Property Hksd = new Property(2, String.class, "hksd", false, "HKSD");
        public final static Property Hksj = new Property(3, String.class, "hksj", false, "HKSJ");
        public final static Property Hkazwz = new Property(4, String.class, "hkazwz", false, "HKAZWZ");
    }


    public Da_shiduDao(DaoConfig config) {
        super(config);
    }
    
    public Da_shiduDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DA_SHIDU' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'HKSDSX' TEXT," + // 1: hksdsx
                "'HKSD' TEXT," + // 2: hksd
                "'HKSJ' TEXT," + // 3: hksj
                "'HKAZWZ' TEXT);"); // 4: hkazwz
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DA_SHIDU'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Da_shidu entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String hksdsx = entity.getHksdsx();
        if (hksdsx != null) {
            stmt.bindString(2, hksdsx);
        }
 
        String hksd = entity.getHksd();
        if (hksd != null) {
            stmt.bindString(3, hksd);
        }
 
        String hksj = entity.getHksj();
        if (hksj != null) {
            stmt.bindString(4, hksj);
        }
 
        String hkazwz = entity.getHkazwz();
        if (hkazwz != null) {
            stmt.bindString(5, hkazwz);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Da_shidu readEntity(Cursor cursor, int offset) {
        Da_shidu entity = new Da_shidu( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // hksdsx
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hksd
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // hksj
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // hkazwz
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Da_shidu entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHksdsx(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHksd(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHksj(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHkazwz(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Da_shidu entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Da_shidu entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
