package com.huimv.yzzs.db.entity;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_SCJ.
 */
public class Da_scj implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
    private String jqid;
    private String rfid;
    private String tw;
    private String cjsj;

    public Da_scj() {
    }

    public Da_scj(Long id) {
        this.id = id;
    }

    public Da_scj(Long id, String jqid, String rfid, String tw, String cjsj) {
        this.id = id;
        this.jqid = jqid;
        this.rfid = rfid;
        this.tw = tw;
        this.cjsj = cjsj;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJqid() {
        return jqid;
    }

    public void setJqid(String jqid) {
        this.jqid = jqid;
    }

    public String getRfid() {
        return rfid;
    }

    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    public String getTw() {
        return tw;
    }

    public void setTw(String tw) {
        this.tw = tw;
    }

    public String getCjsj() {
        return cjsj;
    }

    public void setCjsj(String cjsj) {
        this.cjsj = cjsj;
    }

}
