package com.huimv.yzzs.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DA_WENDU.
 */
public class Da_wendu {

    private Long id;
    private String hkwdsx;
    private String hkwd;
    private String hksj;
    private String hkazwz;

    public Da_wendu() {
    }

    public Da_wendu(Long id) {
        this.id = id;
    }

    public Da_wendu(Long id, String hkwdsx, String hkwd, String hksj, String hkazwz) {
        this.id = id;
        this.hkwdsx = hkwdsx;
        this.hkwd = hkwd;
        this.hksj = hksj;
        this.hkazwz = hkazwz;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHkwdsx() {
        return hkwdsx;
    }

    public void setHkwdsx(String hkwdsx) {
        this.hkwdsx = hkwdsx;
    }

    public String getHkwd() {
        return hkwd;
    }

    public void setHkwd(String hkwd) {
        this.hkwd = hkwd;
    }

    public String getHksj() {
        return hksj;
    }

    public void setHksj(String hksj) {
        this.hksj = hksj;
    }

    public String getHkazwz() {
        return hkazwz;
    }

    public void setHkazwz(String hkazwz) {
        this.hkazwz = hkazwz;
    }

}
