package com.huimv.yzzs.db.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.huimv.yzzs.db.entity.Da_wendu;
import com.huimv.yzzs.db.entity.Da_shidu;
import com.huimv.yzzs.db.entity.Da_anqi;
import com.huimv.yzzs.db.entity.Da_ph;
import com.huimv.yzzs.db.entity.Da_mc;
import com.huimv.yzzs.db.entity.Da_bt;
import com.huimv.yzzs.db.entity.Da_hksj;
import com.huimv.yzzs.db.entity.Da_qk_shuiya;
import com.huimv.yzzs.db.entity.Da_qk_shuiliu;
import com.huimv.yzzs.db.entity.Da_scj;

import com.huimv.yzzs.db.entity.Da_wenduDao;
import com.huimv.yzzs.db.entity.Da_shiduDao;
import com.huimv.yzzs.db.entity.Da_anqiDao;
import com.huimv.yzzs.db.entity.Da_phDao;
import com.huimv.yzzs.db.entity.Da_mcDao;
import com.huimv.yzzs.db.entity.Da_btDao;
import com.huimv.yzzs.db.entity.Da_hksjDao;
import com.huimv.yzzs.db.entity.Da_qk_shuiyaDao;
import com.huimv.yzzs.db.entity.Da_qk_shuiliuDao;
import com.huimv.yzzs.db.entity.Da_scjDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig da_wenduDaoConfig;
    private final DaoConfig da_shiduDaoConfig;
    private final DaoConfig da_anqiDaoConfig;
    private final DaoConfig da_phDaoConfig;
    private final DaoConfig da_mcDaoConfig;
    private final DaoConfig da_btDaoConfig;
    private final DaoConfig da_hksjDaoConfig;
    private final DaoConfig da_qk_shuiyaDaoConfig;
    private final DaoConfig da_qk_shuiliuDaoConfig;
    private final DaoConfig da_scjDaoConfig;

    private final Da_wenduDao da_wenduDao;
    private final Da_shiduDao da_shiduDao;
    private final Da_anqiDao da_anqiDao;
    private final Da_phDao da_phDao;
    private final Da_mcDao da_mcDao;
    private final Da_btDao da_btDao;
    private final Da_hksjDao da_hksjDao;
    private final Da_qk_shuiyaDao da_qk_shuiyaDao;
    private final Da_qk_shuiliuDao da_qk_shuiliuDao;
    private final Da_scjDao da_scjDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        da_wenduDaoConfig = daoConfigMap.get(Da_wenduDao.class).clone();
        da_wenduDaoConfig.initIdentityScope(type);

        da_shiduDaoConfig = daoConfigMap.get(Da_shiduDao.class).clone();
        da_shiduDaoConfig.initIdentityScope(type);

        da_anqiDaoConfig = daoConfigMap.get(Da_anqiDao.class).clone();
        da_anqiDaoConfig.initIdentityScope(type);

        da_phDaoConfig = daoConfigMap.get(Da_phDao.class).clone();
        da_phDaoConfig.initIdentityScope(type);

        da_mcDaoConfig = daoConfigMap.get(Da_mcDao.class).clone();
        da_mcDaoConfig.initIdentityScope(type);

        da_btDaoConfig = daoConfigMap.get(Da_btDao.class).clone();
        da_btDaoConfig.initIdentityScope(type);

        da_hksjDaoConfig = daoConfigMap.get(Da_hksjDao.class).clone();
        da_hksjDaoConfig.initIdentityScope(type);

        da_qk_shuiyaDaoConfig = daoConfigMap.get(Da_qk_shuiyaDao.class).clone();
        da_qk_shuiyaDaoConfig.initIdentityScope(type);

        da_qk_shuiliuDaoConfig = daoConfigMap.get(Da_qk_shuiliuDao.class).clone();
        da_qk_shuiliuDaoConfig.initIdentityScope(type);

        da_scjDaoConfig = daoConfigMap.get(Da_scjDao.class).clone();
        da_scjDaoConfig.initIdentityScope(type);

        da_wenduDao = new Da_wenduDao(da_wenduDaoConfig, this);
        da_shiduDao = new Da_shiduDao(da_shiduDaoConfig, this);
        da_anqiDao = new Da_anqiDao(da_anqiDaoConfig, this);
        da_phDao = new Da_phDao(da_phDaoConfig, this);
        da_mcDao = new Da_mcDao(da_mcDaoConfig, this);
        da_btDao = new Da_btDao(da_btDaoConfig, this);
        da_hksjDao = new Da_hksjDao(da_hksjDaoConfig, this);
        da_qk_shuiyaDao = new Da_qk_shuiyaDao(da_qk_shuiyaDaoConfig, this);
        da_qk_shuiliuDao = new Da_qk_shuiliuDao(da_qk_shuiliuDaoConfig, this);
        da_scjDao = new Da_scjDao(da_scjDaoConfig, this);

        registerDao(Da_wendu.class, da_wenduDao);
        registerDao(Da_shidu.class, da_shiduDao);
        registerDao(Da_anqi.class, da_anqiDao);
        registerDao(Da_ph.class, da_phDao);
        registerDao(Da_mc.class, da_mcDao);
        registerDao(Da_bt.class, da_btDao);
        registerDao(Da_hksj.class, da_hksjDao);
        registerDao(Da_qk_shuiya.class, da_qk_shuiyaDao);
        registerDao(Da_qk_shuiliu.class, da_qk_shuiliuDao);
        registerDao(Da_scj.class, da_scjDao);
    }
    
    public void clear() {
        da_wenduDaoConfig.getIdentityScope().clear();
        da_shiduDaoConfig.getIdentityScope().clear();
        da_anqiDaoConfig.getIdentityScope().clear();
        da_phDaoConfig.getIdentityScope().clear();
        da_mcDaoConfig.getIdentityScope().clear();
        da_btDaoConfig.getIdentityScope().clear();
        da_hksjDaoConfig.getIdentityScope().clear();
        da_qk_shuiyaDaoConfig.getIdentityScope().clear();
        da_qk_shuiliuDaoConfig.getIdentityScope().clear();
        da_scjDaoConfig.getIdentityScope().clear();
    }

    public Da_wenduDao getDa_wenduDao() {
        return da_wenduDao;
    }

    public Da_shiduDao getDa_shiduDao() {
        return da_shiduDao;
    }

    public Da_anqiDao getDa_anqiDao() {
        return da_anqiDao;
    }

    public Da_phDao getDa_phDao() {
        return da_phDao;
    }

    public Da_mcDao getDa_mcDao() {
        return da_mcDao;
    }

    public Da_btDao getDa_btDao() {
        return da_btDao;
    }

    public Da_hksjDao getDa_hksjDao() {
        return da_hksjDao;
    }

    public Da_qk_shuiyaDao getDa_qk_shuiyaDao() {
        return da_qk_shuiyaDao;
    }

    public Da_qk_shuiliuDao getDa_qk_shuiliuDao() {
        return da_qk_shuiliuDao;
    }

    public Da_scjDao getDa_scjDao() {
        return da_scjDao;
    }

}
